ветка спринт 6.
wixpAndrew/java-kanban pull request #1
Opened 2024-10-27 18:09 UTC by wixpAndrew

в ветке описано добавление HistoryList. улучшение историй + юнит тесты улучшены

2024-10-30 21:28 UTC, afomkina requested changes
Нужно поправить структуру пакетов она должна быть следующей

```
src->
    main ->
        java ->
            manager     
            task
            history
    test ->
        java -> 
            manager
            task
            history
```

Во всем проекте поехала разметка, нужно поправить все классы по code-style. Проще всего использовать сочетание клавиш [Ctrl+Alt+L](https://www.jetbrains.com/idea/guide/tips/reformat-file/) в Idea. Оно позволяет быстро подогнать код к корректной разметке

2024-10-30 21:28 UTC, afomkina commented on java-kanban.iml
Удали, пожалуйста, из проекта все лишние файлы (`java-kanban.iml`). 
Чтобы это сделать сначала нужно добавить в файл `.gitignore` строчки 

```
*.iml
```

А потом исключить данный файл из репозитория

2024-10-30 21:28 UTC, afomkina commented on src/model/Epic.java
>      public ArrayList<Subtask> getAllSubTasks() {
Метод должен возвращать интерфейс (List), а не конкретную реализацию. Это сделает программу более гибой и не зависящей от определенной реализации коллекции.
Нужно заменить для всех методов в проекте, которые возвращают `ArrayList`

2024-10-30 21:28 UTC, afomkina commented on src/model/Epic.java
>      public ArrayList<Subtask> getAllSubTasks() {
На 6 строке класса Epic, где создается список связанных с ним подзадач нужно сначала определить интерфейс `private List<Subtask> subList = new ArrayList<>();`, а создавать объект уже с определенной реализацией.
Это тоже сделает программу более гибкой.
Это поле также должно быть `final`

2024-10-30 21:28 UTC, afomkina commented on src/model/Epic.java
> +            if (isNew == true && isDone == false && isInProgress == false) {
Поля `isNew`, `isDone` и `isInProgress` имеют тип boolean, поэтому дополнительно сравнивать его с значениями `true` и `false` не нужно
```suggestion
            if (isNew && !isDone && !isInProgress) {
```

2024-10-30 21:28 UTC, afomkina commented on src/model/Epic.java
> +            } else if (isDone == true && isNew == false && isInProgress == false) {
Здесь нужно поправить в соответствии с комментарием выше

2024-10-30 21:28 UTC, afomkina commented on src/model/Epic.java
>          boolean isNew = false;
Метод пересчета статуса эпиков должен также использоваться при создании подзадачи (метод `createSubtask`), при удалении всех подзадач в методе `removeAllSubs`,

2024-10-30 21:28 UTC, afomkina commented on src/controllers/InMemoryTaskManager.java
>      private  HistoryManager historyManager = null;
Поле должно быть final
```suggestion
    private final HistoryManager historyManager;
```

2024-10-30 21:28 UTC, afomkina commented on src/controllers/InMemoryTaskManager.java
>      private  HistoryManager historyManager = null;
Мапы с задачами тоже должны быть final, а еще они должны быть типа Map:

`private final Map<Integer, Epic> epics = new HashMap<>();`

Поправь для всех

2024-10-30 21:28 UTC, afomkina commented on src/controllers/InMemoryTaskManager.java
Метод со строки 68
```
public Collection<Epic> getAllEpics() {
        return new ArrayList<>(epics.values());
}
```
должен возвращать список, а не коллекцию

2024-10-30 21:28 UTC, afomkina commented on src/controllers/Managers.java
> +    public static ITaskManager getDefault() {
Нужно переименовать интерфейс в `TaskManager`

2024-10-30 21:28 UTC, afomkina commented on src/controllers/HistoryList.java
> +    private class HistoryNode<V> {
Должен быть `static`, так как  не зависит от экземпляра внешнего класса.

2024-10-30 21:28 UTC, afomkina commented on src/controllers/HistoryList.java
> +        public HistoryNode<V> prev;
Поля с модификатором доступа `public` могут быть изменены из внешклассового кода, что может привести к неконтролируемому состоянию объектов `HistoryNode`. Нужно стараться всегда использовать максимально строгий модификатор доступа, чтобы обезопасить код.
Замени модификатор доступа для всех полей класса на `private`

2024-10-30 21:28 UTC, afomkina commented on src/controllers/HistoryList.java
> +    private HashMap<Integer, HistoryNode<Task>> tasksMap;
* Поле `tasksMap` должно быть`final` для обеспечения неизменяемости ссылки (что способствует надежности кода и безопасности при многопоточном программировании) и для упрощения понимания кода другими разработчиками, указывая, что это поле не предназначено для изменения после начальной установки
* При объявлении переменных в Java предпочтительнее использовать интерфейсы (как Map) вместо конкретных реализаций (как HashMap), это повышает гибкость (при переходе к другой реализации достаточно изменить только место инициализации) и обеспечивает инкапсуляцию (скрытие деталей реализации)

2024-10-30 21:28 UTC, afomkina commented on src/controllers/HistoryList.java
> +    HistoryList() {
Конструктор должен быть `publiс`, чтобы можно было создавать объекты менеджера из любой точки программы

2024-10-30 21:28 UTC, afomkina commented on src/controllers/HistoryList.java
> +        ArrayList<Task> result = new ArrayList<>();
```suggestion
        List<Task> result = new ArrayList<>();
```

2024-10-30 21:28 UTC, afomkina commented on src/controllers/InMemoryTaskManager.java
> +        historyManager.remove(taskID);
Метод должен вызываться также и при удалении эпика и подзадачи, а также в методах удаления всех задач по типам

2024-10-30 21:28 UTC, afomkina commented on src/Main.java
> +        InMemoryHistoryManager his = new InMemoryHistoryManager();
История должна вызываться через менеджер задач с помощью метода `getHistory`

2024-10-30 21:28 UTC, afomkina commented on src/Main.java
>          InMemoryTaskManager tm = new InMemoryTaskManager();
Объект менеджера подзадач должен создаваться через "фабрику" Managers методом `getDefault`

2024-10-30 21:28 UTC, afomkina commented on src/Main.java
> +        InMemoryTaskManager taskManager = new InMemoryTaskManager();
Объекты со строк 30 -31 нужно удалить так как они создаются выше

2024-10-30 21:28 UTC, afomkina commented on src/Main.java
> +        List<Task> result = new ArrayList<>();
Этот список не нужен, удали, пожалуйста

2024-10-30 21:28 UTC, afomkina commented on src/Main.java
> +        System.out.println(taskManager.getHistory());
По тз нужно после каждого запроса вывести историю и убедитесь, что в ней нет повторов.

2024-10-30 21:28 UTC, afomkina commented on src/Main.java
> +
Не реализована часть из тз про проверку удаления:
- Удалите задачу, которая есть в истории, и проверьте, что при печати она не будет выводиться.
- Удалите эпик с тремя подзадачами и убедитесь, что из истории удалился как сам эпик, так и все его подзадачи.

2024-10-30 21:28 UTC, afomkina commented on src/Main.java
> +        taskManager.getTaskById(task2.getId());
Этого недостаточно для проверки. По ТЗ нужно запросить созданные задачи несколько раз в разном порядке. Важно также запросить одну и ту же задачу несколько раз, чтобы убедиться, что в истории нет повторов

2024-10-30 21:28 UTC, afomkina commented on test/HistoryListTest.java
> +        InMemoryHistoryManager history = new InMemoryHistoryManager();
Объекты должны создаваться через фабрику Managers, нужно вынести их в переменные класса или метод `@BeforeEach`

2024-10-30 21:28 UTC, afomkina commented on test/HistoryListTest.java
> +        Task task3 = new Task("theiii", "dggg");
Задачи повторяются в каждом из тестов, нужно вынести их в переменные класса или @BeforeEach

2024-10-30 21:28 UTC, afomkina commented on test/EpicTest.java
>              InMemoryTaskManager inMemoryTaskManager = new InMemoryTaskManager();
Должен создаваться черз Manager, нужно вынести создание на уровень класса или в метод [@BeforeEach](https://www.geeksforgeeks.org/junit-5-beforeeach/), чтобы для каждого теста создавался свой `InMemoryTaskManager`

2024-10-30 21:28 UTC, afomkina commented on test/EpicTest.java
>              Epic epic2 = new Epic("name2", "dfdfdfd");
На строке 29, чтобы проверить, что список пуст, создавать новый список не нужно.
Нужно просто сравнить размер
`assertEquals(0, inMemoryTaskManager.getAllEpics().size());`

2024-10-30 21:28 UTC, afomkina commented on test/EpicTest.java
>          assertEquals(taskManager.getAllEpics().size(),  1);
В assertEquals сначала передается ожидаемое значение - 1, а затем актуальное. 
Должно быть наоборот: 
```suggestion
        assertEquals(1, taskManager.getAllEpics().size());
```

2024-10-30 21:28 UTC, afomkina commented on test/TestSubTask.java
>              InMemoryTaskManager inMemoryTaskManager = new InMemoryTaskManager();
Нужно поправить тест как в комментариях выше

2024-10-31 15:17 UTC, wixpAndrew commented on java-kanban.iml
то есть в папке src будет два пакета : test , main?

2024-11-01 13:54 UTC, afomkina requested changes

2024-11-01 13:54 UTC, afomkina commented on src/main/java/history/HistoryList.java
> +    private final HashMap<Integer, HistoryNode<Task>> tasksMap;
Объявлять нужно интерфейс, а создавать объект уже с определенной реализацией

2024-11-01 13:54 UTC, afomkina commented on src/main/java/history/HistoryList.java
> +    private class HistoryNode<V> {
Класс должен быть статическим

2024-11-01 13:54 UTC, afomkina commented on src/main/java/history/HistoryList.java
> +        public HistoryNode<V> prev;
А поля класса 66-68 должны быть приватными

2024-11-01 13:54 UTC, afomkina commented on src/main/java/history/HistoryList.java
> +        public V value;
Поле должно быть final

2024-11-01 13:54 UTC, afomkina commented on src/main/java/manager/HistoryManager.java
> +    void remove(int id);
Метод должен использоваться во всех методах удаления задач по типам в менеджере задач
- deleteAllTasks
- deleteTask
- deleteAllEpics
- deleteEpic
- removeAllSubs
- deleteSub

2024-11-01 13:54 UTC, afomkina commented on src/main/java/manager/ITaskManager.java
>      ArrayList<Task> getTasks();
Должен возвращать интернфейс (List), а не конкретную реализацию

2024-11-01 13:54 UTC, afomkina commented on src/main/java/manager/InMemoryTaskManager.java
> +    private final HashMap<Integer, Subtask> subtasks = new HashMap<>();
Поправь и для мап выше
```suggestion
    private final Map<Integer, Subtask> subtasks = new HashMap<>();
```

2024-11-01 13:54 UTC, afomkina commented on src/main/java/manager/InMemoryTaskManager.java
> +    private HistoryManager historyManager = null;
Должен быть `final`
```suggestion
    private final HistoryManager historyManager;
```

2024-11-01 13:54 UTC, afomkina commented on src/main/java/manager/InMemoryTaskManager.java
Метод с 75 строки должен возвращать список
```
public List<Epic> getAllEpics() {
        return new ArrayList<>(epics.values());
    }
```

2024-11-01 13:54 UTC, afomkina commented on src/main/java/Main.java
> +        InMemoryHistoryManager his = new InMemoryHistoryManager();
Менеджер истории нужно доставать с помощью метода `getHistory()` в менеджере задач

2024-11-01 13:54 UTC, afomkina commented on src/main/java/Main.java
> +        InMemoryTaskManager tm = new InMemoryTaskManager();
Менеджер задач нужно создавать через фабрику `Managers.getDefault();`

2024-11-01 13:54 UTC, afomkina commented on src/main/java/Main.java
> +        InMemoryTaskManager taskManager = new InMemoryTaskManager();
Строки 29-30 нужно удалить, так как они уже созданы на строках 15-16

2024-11-01 13:54 UTC, afomkina commented on src/main/java/Main.java
> +        System.out.println(taskManager.getAllEpics());
Запрашивать нужно задачу по id, чтобы вызывался метод добавлении задачи в историю. После каждого запроса нужно вывести историю и убедитесь, что в ней нет повторов.

2024-11-01 13:54 UTC, afomkina commented on src/main/java/Main.java
> +        taskManager.removeAllSubs();
Удалите задачу, которая есть в истории, и проверьте, что при печати она не будет выводиться

2024-11-01 13:54 UTC, afomkina commented on src/main/java/Main.java
> +        System.out.println(epic1.getAllSubTasks());
Удалите эпик с тремя подзадачами и убедитесь, что из истории удалился как сам эпик, так и все его подзадачи

2024-11-01 13:54 UTC, afomkina commented on src/main/java/Main.java
> +        List<Task> result = new ArrayList<>();
Этот список не нужен, удали его

2024-11-01 13:54 UTC, afomkina commented on test/history/HistoryListTest.java
> +    List<Task> result = new ArrayList<>();
У всех полей класса должен быть модификатор доступа private

2024-11-01 13:54 UTC, afomkina commented on test/history/HistoryListTest.java
> +    InMemoryHistoryManager history = new InMemoryHistoryManager();
Менеджер истории нужно вызывать с помощью метода `getHistory` истории задач

2024-11-01 13:54 UTC, afomkina commented on test/history/HistoryListTest.java
> +    InMemoryTaskManager taskManger = new InMemoryTaskManager();
Менеджер задач нужно создавать с помощью фабрики `Managers.getDefault()`

2024-11-01 13:54 UTC, afomkina commented on test/manager/TestSubTask.java
> +        InMemoryTaskManager inMemoryTaskManager3 = new InMemoryTaskManager();
Нужно вынести создание на уровень класса, создавать через фабрику

2024-11-01 13:54 UTC, afomkina commented on test/task/TaskTest.java
>          InMemoryTaskManager inMemoryTaskManager = new InMemoryTaskManager();
Нужно вынести создание на уровень класса, как и в других тестах. Создавать через фабрику

2024-11-01 13:54 UTC, afomkina commented on test/task/TaskTest.java
>          ArrayList<Task> ar = new ArrayList<>();
```suggestion
        List<Task> ar = new ArrayList<>();
```

2024-11-01 13:54 UTC, afomkina commented on test/history/HistoryListTest.java
> +       assertEquals(taskManger.getHistory(), result);
Нужно проверять количество задач в истории

2024-11-01 13:54 UTC, afomkina commented on test/history/HistoryListTest.java
> +        assertEquals(taskManger.getHistory(), result);
Нужно проверять количество задач в истории

2024-11-01 13:54 UTC, afomkina commented on test/manager/EpicTest.java
> +        assertEquals(inMemoryTaskManager2.getAllEpics(), ar);
Нужно проверить, что количество элементов в списке == 0 или что список пуст isEmpty

2024-11-01 13:54 UTC, afomkina commented on test/manager/TestSubTask.java
> +        assertEquals(ar, inMemoryTaskManager3.getAllEpicSubTasks(epic1.getId()));
Нужно проверить, что список пуст или его размер равен 0

2024-11-02 17:02 UTC, afomkina requested changes

2024-11-02 17:02 UTC, afomkina commented on src/main/java/Main.java
> +        InMemoryHistoryManager his = new InMemoryHistoryManager();
Не исправлено

2024-11-02 17:02 UTC, afomkina commented on src/main/java/history/HistoryList.java
> +    private final HashMap<Integer, HistoryNode<Task>> tasksMap;
Не исправлено

2024-11-02 17:02 UTC, afomkina commented on src/main/java/history/HistoryList.java
> +        ArrayList<Task> result = new ArrayList<>();
```suggestion
        List<Task> result = new ArrayList<>();
```

2024-11-02 17:02 UTC, afomkina commented on src/main/java/history/HistoryList.java
> +        HistoryNode(V value, HistoryNode<V> next, HistoryNode<V> prev) {
Можно тоже сделать `private`

2024-11-02 17:02 UTC, afomkina commented on src/main/java/manager/ITaskManager.java
>      ArrayList<Task> getTasks();
Не исправлено

2024-11-02 17:02 UTC, afomkina commented on src/main/java/manager/InMemoryTaskManager.java
> +        historyManager.remove(taskID);
Метод `historyManager.remove(...);` должен использоваться во всех методах удаления задач по типам в менеджере задач

- deleteAllTasks
- deleteAllEpics
- deleteEpic
- removeAllSubs
- deleteSub

2024-11-02 17:02 UTC, afomkina commented on test/history/HistoryListTest.java
> +    private ITaskManager taskManger = Managers.getDefault();
Поля класса строки (15-19) должны быть `final`

2024-11-02 17:02 UTC, afomkina commented on test/history/HistoryListTest.java
> +    private List<Task> result = new ArrayList<>();
Этот список лишний - его нужно удалить

2024-11-02 17:02 UTC, afomkina commented on test/manager/EpicTest.java
> +        ArrayList<Epic> ar = new ArrayList<>();
Этот список лишний, его нужно удалить

2024-11-02 17:02 UTC, afomkina commented on test/manager/TestSubTask.java
> +        InMemoryTaskManager inMemoryTaskManager3 = new InMemoryTaskManager();
Нужно вынести создание на уровень класса, а не дублировать в каждом из тестов

2024-11-02 17:02 UTC, afomkina commented on test/task/TaskTest.java
> +        ITaskManager inMemoryTaskManager = Managers.getDefault();
Нужно вынести данное поле на уровень класса, а не дулировать создание в каждом из тестов

2024-11-02 17:02 UTC, afomkina commented on test/manager/TestSubTask.java
> +        ArrayList<Subtask> ar = new ArrayList<>();
Этот список не нужен, надо проверять, что размер коллекции равен 2

2024-11-03 13:15 UTC, afomkina requested changes

2024-11-03 13:15 UTC, afomkina commented on src/main/java/manager/ITaskManager.java
>      ArrayList<Task> getTasks();
```suggestion  
    List<Task> getTasks();
```

2024-11-03 13:15 UTC, afomkina commented on test/manager/TestSubTask.java
> +        ArrayList<Subtask> ar = new ArrayList<>();
Эта коллекция больше не нужна, ее надо удалить

2024-11-03 13:15 UTC, afomkina commented on src/main/java/manager/InMemoryTaskManager.java
>      @Override
Метод `public ArrayList<Task> getTasks()` со строки 39
должен возвращать интерфейс : `List<Task> getTasks()`, а не определенную реализацию

2024-11-04 11:44 UTC, afomkina approved these changes

2024-11-12 16:20 UTC, merged